apiVersion: v1
kind: Service
metadata:
  name: node101-service
  labels:
    app: node101
spec:
  selector:
    app: node101

  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
  type: NodePort